volumes:
  auth_postgres_volume:
  prometheus_data:
  grafana_data:
  tasks_postgres_volume:

services:
  auth-pg:
    image: postgres:15-alpine3.17
    env_file:
      - ./auth/local.env
    ports:
      - "54321:5432"
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data

  auth-migrator:
    build:
      context: ./auth
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: auth-pg

  auth-backend:
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "50051:50051"
      - "8080:8080"
      - "8090:8090"
      - "2112:2112"
    env_file: ./auth/local.env
    depends_on:
      - auth-pg

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./auth/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./auth/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  tasks-pg:
    image: postgres:15-alpine3.17
    env_file:
      - ./tasks/.env
    ports:
      - "${POSTGRES_PORT:-54322}:5432"
    volumes:
      - tasks_postgres_volume:/var/lib/postgresql/data

  tasks-migrator:
    build:
      context: ./tasks
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: tasks-pg

  tasks-backend:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8081:8081"
    env_file: ./tasks/.env
    depends_on:
      - tasks-pg

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 3
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
